input {
  beats {
    host => "0.0.0.0"
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    user => "${ELASTIC_USER}"
    password => "${ELASTIC_PASSWORD}"
    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/certs/ca/ca.crt"]
    index => "ncs-windows-pqc-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
